Add colour support and bump version number to 1.0.1c
reupen/console_panel pull request #10
Opened 2021-08-10 20:13 UTC by rplociennik

For what it's worth, this change adds colour support to the panel. Something that's been bugging me for a while now.

Seeing that this component has been acting as a demo component of sorts, I'm not sure how desirable this change might be...

2021-08-11 16:18 UTC, reupen requested changes
This looks generally good to me 👍 

I've left some very minor comments. Let me know if you're OK to do those. (Also don't worry about the failing build – I'll fix that later.)

One thing I was a bit worried about was that the default background colour will change from grey to white (with default Windows colours), but I see even the Default UI does this now so I think it's fine.

2021-08-11 16:18 UTC, reupen commented on foo_uie_console/main.cpp
> +        return (INT_PTR)s_brush;
I think the example from Microsoft Docs must be using `INT_PTR` for a dialog box procedure (`DLGPROC`), I'd switch to using a C++ cast to an `LRESULT`:

```suggestion
        return reinterpret_cast<LRESULT>(s_brush);
```

2021-08-11 16:18 UTC, reupen commented on foo_uie_console/main.cpp
> +    case WM_CTLCOLORSTATIC: {
Would be good to move the `WM_CTLCOLORSTATIC` case up to, say, just before `WM_ERASEBKGND` (seems like a more logical position based on the current order of the messages).

2021-08-11 16:56 UTC, rplociennik commented
Thanks for a swift review. I don't think there's a single remark I wouldn't agree with. I'll address these ASAP.

I bet the build process hasn't been updated since the component was last built. I figured it would be a non issue.

> One thing I was a bit worried about was that the default background colour will change from grey to white (with default Windows colours), but I see even the Default UI does this now so I think it's fine.

That also bothered me a little. I don't think that specifying default custom colours for a component would be that straightforward, but, then again, I'm not sure if any other component does that. All in all, I'm glad you won't miss the greys. ;)

2021-08-12 16:37 UTC, reupen approved these changes
Thanks 👍

2021-08-12 16:38 UTC, merged